# Generated by Django 6.0 on 2026-01-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bls_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('energy_in_kj_per_100g', models.FloatField()),
                ('energy_in_kcal_per_100g', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlanFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.food')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealplan')),
            ],
            options={
                'unique_together': {('meal_plan', 'food')},
            },
        ),
        migrations.AddField(
            model_name='mealplan',
            name='foods',
            field=models.ManyToManyField(related_name='meal_plans', through='meals.MealPlanFood', to='meals.food'),
        ),
    ]
