# Generated by Django 6.0 on 2026-01-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="mealplan",
            options={"ordering": ["-creation_date"]},
        ),
    ]
