# Generated by Django 6.0 on 2026-01-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_mealplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fat_in_g_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='fibre_in_g_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='iron_in_mg_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='protein_in_g_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar_in_g_per_100g',
            field=models.FloatField(default=0.0),
        ),
    ]
