# Generated by Django 6.0 on 2026-01-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0005_food_fat_in_g_per_100g_food_fibre_in_g_per_100g_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="calcium_in_mg_per_100g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="food",
            name="magnesium_in_mg_per_100g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="food",
            name="omega3_in_g_per_100g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="food",
            name="vita_in_mug_per_100g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="food",
            name="vitb12_in_mug_per_100g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="food",
            name="vitc_in_mg_per_100g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="food",
            name="vitd_in_mug_per_100g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="food",
            name="zinc_in_mg_per_100g",
            field=models.FloatField(default=0.0),
        ),
    ]
