# Generated by Django 6.0 on 2026-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0006_food_calcium_in_mg_per_100g_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="visible_nutrients",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
