# Generated by Django 6.0 on 2026-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_mealplan_alter_mealplanday_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplanday',
            name='visible_nutrients',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='visible_nutrients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
