# Generated by Django 6.0 on 2026-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_remove_mealplanday_visible_nutrients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='carbohydrate_in_g_per_100g',
            field=models.FloatField(default=0.0),
        ),
    ]
