# Generated by Django 6.0 on 2026-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0012_food_carbohydrate_in_g_per_100g"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="thresholds",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
