# Generated by Django 6.0 on 2026-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_mealplan_thresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('energy_in_kj_min', models.FloatField(blank=True, null=True)),
                ('energy_in_kj_max', models.FloatField(blank=True, null=True)),
                ('energy_in_kcal_min', models.FloatField(blank=True, null=True)),
                ('energy_in_kcal_max', models.FloatField(blank=True, null=True)),
                ('protein_in_g_min', models.FloatField(blank=True, null=True)),
                ('protein_in_g_max', models.FloatField(blank=True, null=True)),
                ('fat_in_g_min', models.FloatField(blank=True, null=True)),
                ('fat_in_g_max', models.FloatField(blank=True, null=True)),
                ('carbohydrate_in_g_min', models.FloatField(blank=True, null=True)),
                ('carbohydrate_in_g_max', models.FloatField(blank=True, null=True)),
                ('fibre_in_g_min', models.FloatField(blank=True, null=True)),
                ('fibre_in_g_max', models.FloatField(blank=True, null=True)),
                ('iron_in_mg_min', models.FloatField(blank=True, null=True)),
                ('iron_in_mg_max', models.FloatField(blank=True, null=True)),
                ('sugar_in_g_min', models.FloatField(blank=True, null=True)),
                ('sugar_in_g_max', models.FloatField(blank=True, null=True)),
                ('omega3_in_g_min', models.FloatField(blank=True, null=True)),
                ('omega3_in_g_max', models.FloatField(blank=True, null=True)),
                ('vitc_in_mg_min', models.FloatField(blank=True, null=True)),
                ('vitc_in_mg_max', models.FloatField(blank=True, null=True)),
                ('magnesium_in_mg_min', models.FloatField(blank=True, null=True)),
                ('magnesium_in_mg_max', models.FloatField(blank=True, null=True)),
                ('zinc_in_mg_min', models.FloatField(blank=True, null=True)),
                ('zinc_in_mg_max', models.FloatField(blank=True, null=True)),
                ('vitb12_in_mug_min', models.FloatField(blank=True, null=True)),
                ('vitb12_in_mug_max', models.FloatField(blank=True, null=True)),
                ('vita_in_mug_min', models.FloatField(blank=True, null=True)),
                ('vita_in_mug_max', models.FloatField(blank=True, null=True)),
                ('calcium_in_mg_min', models.FloatField(blank=True, null=True)),
                ('calcium_in_mg_max', models.FloatField(blank=True, null=True)),
                ('vitd_in_mug_min', models.FloatField(blank=True, null=True)),
                ('vitd_in_mug_max', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
