# Generated by Django 6.0 on 2026-01-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_thresholdpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdpreset',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
