# Generated by Django 6.0 on 2026-01-21 12:21

import meals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_alter_thresholdpreset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='visible_nutrients',
            field=models.JSONField(blank=True, default=meals.models.get_default_visible_nutrients),
        ),
    ]
