# Generated by Django 6.0 on 2026-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0016_alter_mealplan_visible_nutrients"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplanday",
            name="removed",
            field=models.BooleanField(default=False),
        ),
    ]
