# Generated by Django 6.0 on 2026-02-19 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0018_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=255)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="meals.food",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Alias",
                "verbose_name_plural": "Food Aliases",
                "ordering": ["alias"],
                "unique_together": {("food", "alias")},
            },
        ),
    ]
