# Generated by Django 6.0 on 2026-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0018_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="mealplanfood",
            name="export_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
