# Generated by Django 6.0 on 2026-02-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0019_foodalias"),
        ("meals", "0019_mealplan_subtitle_mealplanfood_export_name"),
    ]

    operations = []
