# Generated by Django 6.0 on 2026-02-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0020_merge_20260220_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='biotin_in_mug_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='copper_in_mug_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='iodine_in_mug_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='manganese_in_mug_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='vitb1_in_mg_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='vitb2_in_mg_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='vitb3_in_mg_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='vitb5_in_mg_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='vitb6_in_mug_per_100g',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='biotin_in_mug_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='biotin_in_mug_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='copper_in_mug_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='copper_in_mug_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='iodine_in_mug_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='iodine_in_mug_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='manganese_in_mug_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='manganese_in_mug_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb1_in_mg_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb1_in_mg_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb2_in_mg_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb2_in_mg_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb3_in_mg_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb3_in_mg_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb5_in_mg_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb5_in_mg_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb6_in_mug_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdpreset',
            name='vitb6_in_mug_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
