# Generated by Django 6.0 on 2026-03-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0025_backgroundjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="pdf_footer_line_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text shown as a light-gray left-aligned footer line on each page of the PDF export.",
                max_length=500,
            ),
        ),
    ]
