# Generated by Django 6.0 on 2026-03-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0026_sitesettings_pdf_footer_line_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="water_in_g_per_100g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="thresholdpreset",
            name="water_in_g_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thresholdpreset",
            name="water_in_g_min",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
