---
- name: Build, Push, and Deploy to Kubernetes
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
    - ../../../ansible/vault.yml
  vars:
    docker_user: "{{ lookup('env', 'DOCKER_USER') }}"
    docker_password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
    image_name: "{{ lookup('env', 'DOCKER_IMAGE') }}"
    project_root: "../../../"

  tasks:
    - name: Ensure environment is specified
      fail:
        msg: "Please specify environment with -e env=prod|dev"
      when: env is not defined

    - name: Set environment-specific variables
      set_fact:
        namespace: "{{ 'meal-plan-analyzer' if env == 'prod' else 'meal-plan-analyzer-dev' }}"
        image_tag: "{{ 'latest' if env == 'prod' else 'dev' }}"

    - name: Set full image name
      set_fact:
        full_image_name: "{{ image_name }}:{{ image_tag }}"

    - name: Ensure Docker variables are provided
      fail:
        msg: "Please provide 'DOCKER_USER' and 'DOCKER_PASSWORD' in the environment"
      when: docker_user == "" or docker_password == ""

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
        registry_url: index.docker.io

    - name: Build Docker image
      community.docker.docker_image_build:
        path: "{{ project_root }}"
        name: "{{ full_image_name }}"
        tag: "{{ image_tag }}"
        rebuild: "always"
        outputs:
          - type: "docker"
            name: "{{ full_image_name }}"
            push: true

    - name: Push Docker image
      community.docker.docker_image_push:
        name: "{{ full_image_name }}"

    - name: Create Docker Registry Secret
      shell: >
        kubectl create secret docker-registry regcred -n {{ namespace }}
        --docker-server=https://index.docker.io/v1/
        --docker-username={{ docker_user }}
        --docker-password={{ docker_password }}
        --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply Kubernetes manifests with Kustomize
      shell: kubectl apply -k ../k8s/overlays/{{ env }}/

    - name: Restart Deployment
      shell: kubectl rollout restart deployment/meal-plan-analyzer -n {{ namespace }}
