apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-plan-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meal-plan-analyzer
  template:
    metadata:
      labels:
        app: meal-plan-analyzer
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: build-scss
          image: image_name
          imagePullPolicy: Always
          command: ["python", "manage.py", "build_scss"]
          envFrom:
            - configMapRef:
                name: meal-plan-analyzer-config
            - secretRef:
                name: meal-plan-analyzer-secret
          volumeMounts:
            - name: sass-cache
              mountPath: /app/sass_cache
        - name: collect-static
          image: image_name
          imagePullPolicy: Always
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          envFrom:
            - configMapRef:
                name: meal-plan-analyzer-config
            - secretRef:
                name: meal-plan-analyzer-secret
          volumeMounts:
            - name: staticfiles
              mountPath: /app/staticfiles
            - name: sass-cache
              mountPath: /app/sass_cache
        - name: migrate
          image: image_name
          imagePullPolicy: Always
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: meal-plan-analyzer-config
            - secretRef:
                name: meal-plan-analyzer-secret
        - name: import-foods
          image: image_name
          imagePullPolicy: Always
          command: ["python", "manage.py", "import_foods", "https://blsdb.de/assets/uploads/BLS_4_0_2025_DE.zip"]
          envFrom:
            - configMapRef:
                name: meal-plan-analyzer-config
            - secretRef:
                name: meal-plan-analyzer-secret
      containers:
        - name: meal-plan-analyzer
          image: image_name
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: meal-plan-analyzer-config
            - secretRef:
                name: meal-plan-analyzer-secret
          volumeMounts:
            - name: staticfiles
              mountPath: /app/staticfiles
            - name: media
              mountPath: /app/media
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: staticfiles
          emptyDir: {}
        - name: sass-cache
          emptyDir: {}
        - name: media
          persistentVolumeClaim:
            claimName: meal-plan-analyzer-media-pvc
