apiVersion: v1
kind: Secret
metadata:
  name: meal-planner-secret
  namespace: meal-planner
stringData:
  SECRET_KEY: "{{ meal_planner_secret_key }}"
  DATABASE_URL: "postgresql://meal_planner:{{ meal_planner_db_password }}@pgcluster-rw.cloudnative-pg.svc.cluster.local:5432/meal_planner"
