apiVersion: v1
kind: Service
metadata:
  name: meal-planner-service
  namespace: meal-planner
spec:
  selector:
    app: meal-planner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
