---
# Need to do it manually, because the declerative way of the cloudnative-pg operator does not work as expected
- name: Fetch meal_planner database user existance
  ansible.builtin.shell:
    cmd: |
      echo "SELECT 1 FROM pg_authid WHERE rolname='meal_planner';" | kubectl cnpg -n cloudnative-pg psql pgcluster
  register: psql_meal_planner_user_exist_result
  changed_when: psql_meal_planner_user_exist_result.rc == 0
- name: Set user existance fact
  ansible.builtin.set_fact:
    psql_meal_planner_user_exist: "{{ psql_meal_planner_user_exist_result.stdout_lines | length > 3 }}" # Found if more than 3 rows are present in the stdout
- name: Create database user
  ansible.builtin.shell:
    cmd: |
      echo "CREATE USER meal_planner WITH PASSWORD {{ meal_planner_db_password }};" | kubectl cnpg -n cloudnative-pg psql pgcluster
  register: psql_database_creation_result
  when: not psql_meal_planner_user_exist
  changed_when: psql_database_creation_result.rc == 0
- name: Fetch meal_planner database existance
  ansible.builtin.shell:
    cmd: |
      echo "SELECT 1 FROM pg_database WHERE datname='meal_planner';" | kubectl cnpg -n cloudnative-pg psql pgcluster
  register: psql_meal_planner_database_exist_result
  changed_when: psql_meal_planner_database_exist_result.rc == 0
- name: Set database existance fact
  ansible.builtin.set_fact:
    psql_meal_planner_database_exist: "{{ psql_meal_planner_database_exist_result.stdout_lines | length > 3 }}" # Found if more than 3 rows are present in the stdout
- name: Create database
  ansible.builtin.shell:
    cmd: |
      echo "CREATE DATABASE meal_planner WITH OWNER meal_planner;" | kubectl cnpg -n cloudnative-pg psql pgcluster
  register: psql_database_creation_result
  when: not psql_meal_planner_database_exist
  changed_when: psql_database_creation_result.rc == 0