apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: meal-plan-analyzer-dev

resources:
  - ingress.yaml
  - ../../base

images:
  - name: image_name
    newName: "index.docker.io/amjadsaadeh/meal-plan-analyzer"
    newTag: "dev"

patches:
  - path: superuser-patch.yaml
    target:
      kind: Deployment
      name: meal-plan-analyzer
