apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: meal-plan-analyzer-dev

resources:
  - ingress.yaml
  - ../../base
  - cnpg-cluster.yaml

images:
  - name: image_name
    newName: "index.docker.io/amjadsaadeh/meal-plan-analyzer"
    newTag: "dev"

patches:
  - path: cnpg-cluster-patch.yaml
    target:
      kind: Cluster
      name: meal-plan-analyzer-db
