apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-analyzer
spec:
  template:
    spec:
      containers:
        - name: meal-analyzer
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
