---
- name: Set A record for mealplanner
  community.general.netcup_dns:
    api_key: "{{ netcup_dns_api_key }}"
    api_password: "{{ netcup_dns_api_password }}"
    customer_id: "{{ netcup_dns_api_usernumber }}"
    domain: "{{ tld }}"
    name: "mealplanner"
    type: "A"
    value: "{{ mealplanner_ipv4_addr }}"
    solo: true
  delegate_to: localhost
  connection: local

- name: Set AAAA record for mealplanner
  community.general.netcup_dns:
    api_key: "{{ netcup_dns_api_key }}"
    api_password: "{{ netcup_dns_api_password }}"
    customer_id: "{{ netcup_dns_api_usernumber }}"
    domain: "{{ tld }}"
    name: "mealplanner"
    type: "AAAA"
    value: "{{ mealplanner_ipv6_addr }}"
    solo: true
  delegate_to: localhost
  connection: local
